name: Build project

on: [push, pull_request]

env :
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  checkLicense:
    name: Check Unity License
    runs-on: ubuntu-latest
    steps:
      - name: Fail - No License
        if: ${{ !startsWith(evn.UNITY_LICENSE, '<') }}
        run: exit 1